[package]
name = "plague"
version = "0.0.0"
authors.workspace = true
publish = false
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true

near-primitives = { path = "../../core/primitives" }
